- name: create GCTA directory structure
  file:
    path: "/var/www/html/cnsgenomics.com/software/{{ item }}"
    state: directory
    mode: 0755
    owner: apache
    group: apache
  with_items:
    - "gcta"
    - "gcta/bin"
    - "gcta/pre_gcta"
    - "gcta/res"
    - "gcta/static"
    - "gcta/static/css"
    - "gcta/static/js"

- name: install GCTA files
  copy:
    src: "{{ role_path }}/files/build/{{ item }}"
    dest: "/var/www/html/cnsgenomics.com/software/gcta/{{ item }}"
    owner: apache
    group: apache
    mode: 0644
  with_items:
    - "greml_ldms.html"
    - "index.html"
    - static/css/atom-one-light.css
    - static/css/bootstrap.min.css
    - static/css/jquery.tocify.css
    - static/css/main.css
    - static/css/solarized-light.css
    - static/js/bootstrap.min.js
    - static/js/hljs.js
    - static/js/jquery-1.12.4.min.js
    - static/js/jquery.tocify.js
    - static/js/jquery.tocify.ori.js
    - static/js/jquery-ui.min.js

- name: install GCTA binaries
  copy:
    src: "{{ role_path }}/files/build/bin/"
    dest: "/var/www/html/cnsgenomics.com/software/gcta/bin/"
    owner: apache
    group: apache
    mode: 0644

- name: install old GCTA binaries
  copy:
    src: "{{ role_path }}/files/build/pre_gcta/"
    dest: "/var/www/html/cnsgenomics.com/software/gcta/pre_gcta/"
    owner: apache
    group: apache
    mode: 0644