---

- name: web server provisioning
  hosts: pctg_web
  
  roles:
    - update
    - fail2ban
    - mariadb
    - php
    - apache
    - software
    - drupal
    - storage
    - letsencrypt
    - saghaus