- name: create ABC directory structure
  file:
    path: "/srv/shiny-server/{{ item }}"
    state: directory
    mode: 0755
    owner: shiny
    group: shiny
  with_items:
    - "abc"
    - "abc/www"
    - "abc/www/img"
    - "abc/www/js"

- name: install ABC files
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/srv/shiny-server/abc/{{ item }}"
    owner: shiny
    group: shiny
    mode: 0644
  with_items:
    - "custom_html.R"
    - "functions.R"
    - "server.R"
    - "ui.R"
    - "www/img/GitHub-Mark-120px-plus.png"
    - "www/js/ga.js"
