- name: install mariadb
  dnf:
    name:
      - mariadb-server
      - python3-PyMySQL
    state: latest

- name: start and enable the service
  service: name=mariadb state=started enabled=yes

- name: delete anonymous users
  mysql_user: user='' host_all=yes state='absent'

- name: disallow remote root login
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: drop test database
  mysql_db: db=test state=absent

- name: set root password
  mysql_user: user=root host={{ item }} password={{ mariadb_root_pass }}
  with_items:
    - '127.0.0.1'
    - '::1'
    - 'localhost'
