- name: install the latest version of fail2ban
  dnf:
    name: fail2ban
    state: latest
  notify:
    - restart fail2ban
  become: yes

- name: start and enable service
  systemd:
    name: "fail2ban.service"
    enabled: yes
    state: started
    daemon-reload: yes
  become: yes
