- name: create GCTB directory structure
  file:
    path: "/var/www/html/cnsgenomics.com/software/{{ item }}"
    state: directory
    mode: 0755
    owner: apache
    group: apache
  with_items:
    - "gctb"
    - "gctb/download"
    - "gctb/fig"
    - "gctb/static"
    - "gctb/static/css"
    - "gctb/static/js"

- name: install GCTB files
  copy:
    src: "{{ role_path }}/files/build/{{ item }}"
    dest: "/var/www/html/cnsgenomics.com/software/gctb/{{ item }}"
    owner: apache
    group: apache
    mode: 0644
  with_items:
    - "index.html"
    - static/css/atom-one-light.css
    - static/css/bootstrap.min.css
    - static/css/jquery.tocify.css
    - static/css/main.css
    - static/css/solarized-light.css
    - static/js/bootstrap.min.js
    - static/js/hljs.js
    - static/js/jquery-1.12.4.min.js
    - static/js/jquery.tocify.js
    - static/js/jquery.tocify.ori.js
    - static/js/jquery-ui.min.js

- name: install GCTB binaries
  copy:
    src: "{{ role_path }}/files/build/download/"
    dest: "/var/www/html/cnsgenomics.com/software/gctb/download/"
    owner: apache
    group: apache
    mode: 0644

- name: install GCTB figures
  copy:
    src: "{{ role_path }}/files/build/fig/"
    dest: "/var/www/html/cnsgenomics.com/software/gctb/fig/"
    owner: apache
    group: apache
    mode: 0644