- name: install needed R libraries
  cran: name={{ item }} state=present
  with_items:
    - data.table
    - DT
    - qqman

- name: create SMRdb directory structure
  file:
    path: "/srv/shiny-server/{{ item }}"
    state: directory
    mode: 0755
    owner: shiny
    group: shiny
  with_items:
    - "SMRdb"
    - "SMRdb/Data"
    - "SMRdb/www"

- name: install SMRdb files
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/srv/shiny-server/SMRdb/{{ item }}"
    owner: shiny
    group: shiny
    mode: 0644
  with_items:
    - "global.R"
    - "server.R"
    - "ui.R"
    - "Data/GWASpubdata.csv"
    - "Data/RegAssocData.csv"
    - "Data/SMR_Database.csv"
    - "www/alz_ilmn_1806721.pdf"
    - "www/alz_ilmn_2370336.pdf"
    - "www/bip1_ilmn_1665280.pdf"
    - "www/bmi_ilmn_1658464.pdf"
    - "www/bmi_ilmn_1680132.pdf"
    - "www/bmi_ilmn_1686516.pdf"
    - "www/bmi_ilmn_1693394.pdf"
    - "www/bmi_ilmn_1696463.pdf"
    - "www/bmi_ilmn_1719097.pdf"
    - "www/bmi_ilmn_1738369.pdf"
    - "www/bmi_ilmn_1781184.pdf"
    - "www/bmi_ilmn_2134224.pdf"
    - "www/cad_ilmn_1696394.pdf"
    - "www/cad_ilmn_1712430.pdf"
    - "www/cad_ilmn_1713380.pdf"
    - "www/cad_ilmn_1785175.pdf"
    - "www/cad_ilmn_2190084.pdf"
    - "www/cd_ilmn_1662174.pdf"
    - "www/cd_ilmn_1671565.pdf"
    - "www/cd_ilmn_1677877.pdf"
    - "www/cd_ilmn_1708375.pdf"
    - "www/cd_ilmn_1712532.pdf"
    - "www/cd_ilmn_1718852.pdf"
    - "www/cd_ilmn_1728298.pdf"
    - "www/cd_ilmn_1738369.pdf"
    - "www/cd_ilmn_2122952.pdf"
    - "www/cd_ilmn_2183687.pdf"
    - "www/cd_ilmn_2401978.pdf"
    - "www/college_ilmn_1723684.pdf"
    - "www/cpd_ilmn_1682098.pdf"
    - "www/cpd_ilmn_2198376.pdf"
    - "www/eduyears_ilmn_1718023.pdf"
    - "www/eduyears_ilmn_1738369.pdf"
    - "www/eduyears_ilmn_2343048.pdf"
    - "www/hdl_ilmn_1677877.pdf"
    - "www/hdl_ilmn_1684227.pdf"
    - "www/hdl_ilmn_1685810.pdf"
    - "www/hdl_ilmn_1689156.pdf"
    - "www/hdl_ilmn_1703335.pdf"
    - "www/hdl_ilmn_1738239.pdf"
    - "www/hdl_ilmn_1754489.pdf"
    - "www/hdl_ilmn_1759983.pdf"
    - "www/hdl_ilmn_1815102.pdf"
    - "www/hdl_ilmn_2341487.pdf"
    - "www/hdl_ilmn_2388507.pdf"
    - "www/hdl_ilmn_2410909.pdf"
    - "www/height_ilmn_1652989.pdf"
    - "www/height_ilmn_1655117.pdf"
    - "www/height_ilmn_1662839.pdf"
    - "www/height_ilmn_1668721.pdf"
    - "www/height_ilmn_1672176.pdf"
    - "www/height_ilmn_1676745.pdf"
    - "www/height_ilmn_1677963.pdf"
    - "www/height_ilmn_1682929.pdf"
    - "www/height_ilmn_1684549.pdf"
    - "www/height_ilmn_1691930.pdf"
    - "www/height_ilmn_1699856.pdf"
    - "www/height_ilmn_1700727.pdf"
    - "www/height_ilmn_1703754.pdf"
    - "www/height_ilmn_1707051.pdf"
    - "www/height_ilmn_1708619.pdf"
    - "www/height_ilmn_1712532.pdf"
    - "www/height_ilmn_1724734.pdf"
    - "www/height_ilmn_1727389.pdf"
    - "www/height_ilmn_1732452.pdf"
    - "www/height_ilmn_1737561.pdf"
    - "www/height_ilmn_1737857.pdf"
    - "www/height_ilmn_1738642.pdf"
    - "www/height_ilmn_1744268.pdf"
    - "www/height_ilmn_1745148.pdf"
    - "www/height_ilmn_1746696.pdf"
    - "www/height_ilmn_1746846.pdf"
    - "www/height_ilmn_1752404.pdf"
    - "www/height_ilmn_1754370.pdf"
    - "www/height_ilmn_1757636.pdf"
    - "www/height_ilmn_1765851.pdf"
    - "www/height_ilmn_1769031.pdf"
    - "www/height_ilmn_1769394.pdf"
    - "www/height_ilmn_1773780.pdf"
    - "www/height_ilmn_1778132.pdf"
    - "www/height_ilmn_1778371.pdf"
    - "www/height_ilmn_1781623.pdf"
    - "www/height_ilmn_1784540.pdf"
    - "www/height_ilmn_1787186.pdf"
    - "www/height_ilmn_1795639.pdf"
    - "www/height_ilmn_1796490.pdf"
    - "www/height_ilmn_1797893.pdf"
    - "www/height_ilmn_1798654.pdf"
    - "www/height_ilmn_1799604.pdf"
    - "www/height_ilmn_1800976.pdf"
    - "www/height_ilmn_1802457.pdf"
    - "www/height_ilmn_1804611.pdf"
    - "www/height_ilmn_1811301.pdf"
    - "www/height_ilmn_1813489.pdf"
    - "www/height_ilmn_1813833.pdf"
    - "www/height_ilmn_1823112.pdf"
    - "www/height_ilmn_1858599.pdf"
    - "www/height_ilmn_2044085.pdf"
    - "www/height_ilmn_2050911.pdf"
    - "www/height_ilmn_2055700.pdf"
    - "www/height_ilmn_2094776.pdf"
    - "www/height_ilmn_2097954.pdf"
    - "www/height_ilmn_2151488.pdf"
    - "www/height_ilmn_2152465.pdf"
    - "www/height_ilmn_2201596.pdf"
    - "www/height_ilmn_2256765.pdf"
    - "www/height_ilmn_2290118.pdf"
    - "www/height_ilmn_2298860.pdf"
    - "www/height_ilmn_2312719.pdf"
    - "www/height_ilmn_2336609.pdf"
    - "www/height_ilmn_2364022.pdf"
    - "www/height_ilmn_2364535.pdf"
    - "www/height_ilmn_2370872.pdf"
    - "www/height_ilmn_2378048.pdf"
    - "www/height_ilmn_2388507.pdf"
    - "www/height_ilmn_2394250.pdf"
    - "www/height_ilmn_2412336.pdf"
    - "www/ibd_ilmn_1671565.pdf"
    - "www/ibd_ilmn_1677877.pdf"
    - "www/ibd_ilmn_1684628.pdf"
    - "www/ibd_ilmn_1697409.pdf"
    - "www/ibd_ilmn_1708375.pdf"
    - "www/ibd_ilmn_1710571.pdf"
    - "www/ibd_ilmn_1712532.pdf"
    - "www/ibd_ilmn_1718023.pdf"
    - "www/ibd_ilmn_1727709.pdf"
    - "www/ibd_ilmn_1738369.pdf"
    - "www/ibd_ilmn_1744713.pdf"
    - "www/ibd_ilmn_1785252.pdf"
    - "www/ibd_ilmn_2300695.pdf"
    - "www/ibd_ilmn_2401978.pdf"
    - "www/ldl_ilmn_1718706.pdf"
    - "www/ldl_ilmn_1744268.pdf"
    - "www/ldl_ilmn_1752046.pdf"
    - "www/ldl_ilmn_1764709.pdf"
    - "www/ldl_ilmn_1796490.pdf"
    - "www/ldl_ilmn_1804148.pdf"
    - "www/ldl_ilmn_2370872.pdf"
    - "www/ra_ilmn_1668277.pdf"
    - "www/ra_ilmn_1670134.pdf"
    - "www/ra_ilmn_1687213.pdf"
    - "www/ra_ilmn_1691693.pdf"
    - "www/ra_ilmn_1698218.pdf"
    - "www/ra_ilmn_1699599.pdf"
    - "www/ra_ilmn_1738369.pdf"
    - "www/ra_ilmn_1797428.pdf"
    - "www/ra_ilmn_1798947.pdf"
    - "www/ra_ilmn_1810875.pdf"
    - "www/ra_ilmn_2075065.pdf"
    - "www/ra_ilmn_2341724.pdf"
    - "www/scz_ilmn_1656427.pdf"
    - "www/scz_ilmn_1673682.pdf"
    - "www/scz_ilmn_1679358.pdf"
    - "www/scz_ilmn_1682098.pdf"
    - "www/scz_ilmn_1706075.pdf"
    - "www/scz_ilmn_1709814.pdf"
    - "www/scz_ilmn_1722309.pdf"
    - "www/scz_ilmn_1728514.pdf"
    - "www/scz_ilmn_1761010.pdf"
    - "www/scz_ilmn_1765649.pdf"
    - "www/scz_ilmn_1786843.pdf"
    - "www/scz_ilmn_1788211.pdf"
    - "www/scz_ilmn_1802380.pdf"
    - "www/scz_ilmn_1811650.pdf"
    - "www/scz_ilmn_2180371.pdf"
    - "www/scz_ilmn_2343047.pdf"
    - "www/scz_ilmn_2347592.pdf"
    - "www/tc_ilmn_1689156.pdf"
    - "www/tc_ilmn_1704253.pdf"
    - "www/tc_ilmn_1731275.pdf"
    - "www/tc_ilmn_1744268.pdf"
    - "www/tc_ilmn_1752046.pdf"
    - "www/tc_ilmn_1796490.pdf"
    - "www/tc_ilmn_1804148.pdf"
    - "www/tc_ilmn_2370872.pdf"
    - "www/tc_ilmn_2372011.pdf"
    - "www/tg_ilmn_1670096.pdf"
    - "www/tg_ilmn_1693394.pdf"
    - "www/uc_ilmn_1683811.pdf"
    - "www/uc_ilmn_1697409.pdf"
    - "www/uc_ilmn_1712532.pdf"
    - "www/uc_ilmn_1718023.pdf"
    - "www/uc_ilmn_1727709.pdf"
    - "www/uc_ilmn_1744713.pdf"
    - "www/uq_imb_logo.png"
    - "www/uq_pctg.png"
    - "www/whradjbmi_ilmn_1657810.pdf"
    - "www/whradjbmi_ilmn_1722025.pdf"
