- name: create a new database for Drupal
  mysql_db:
    name=drupal
    login_password={{ mariadb_root_pass }}
    state=present

- name: create a new database user for Drupal
  mysql_user: >
    name=drupal
    password={{ mariadb_drupal_pass }}
    priv=drupal.*:ALL
    login_password={{ mariadb_root_pass }}
    state=present
    host=localhost
    
# The repo is manually cloned.
# Ownership of at least site/default/files needs to be apache:apache
# HSU drupal team manages this

- name: install apache configuration
  template:
    src: cnsgenomics.com.conf.j2
    dest: /etc/httpd/conf.d/cnsgenomics.com.conf
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - restart httpd
