- name: install mod_ssl
  dnf:
    name:
      - mod_ssl
    state: latest

# https://www.itzgeek.com/how-tos/linux/centos-how-tos/how-to-setup-lets-encrypt-ssl-certificate-with-apache-on-rhel-8-centos-7-rhel-7.html
# https://linuxize.com/post/secure-apache-with-let-s-encrypt-on-centos-8/