- name: create OSCA directory structure
  file:
    path: "/var/www/html/cnsgenomics.com/software/{{ item }}"
    state: directory
    mode: 0755
    owner: apache
    group: apache
  with_items:
    - "osca"
    - "osca/download"
    - "osca/static"
    - "osca/static/css"
    - "osca/static/js"

- name: install OSCA files
  copy:
    src: "{{ role_path }}/files/build/{{ item }}"
    dest: "/var/www/html/cnsgenomics.com/software/osca/{{ item }}"
    owner: apache
    group: apache
    mode: 0644
  with_items:
    - "index.html"
    - static/css/atom-one-light.css
    - static/css/bootstrap.min.css
    - static/css/jquery.tocify.css
    - static/css/main.css
    - static/css/solarized-light.css
    - static/js/bootstrap.min.js
    - static/js/hljs.js
    - static/js/jquery-1.12.4.min.js
    - static/js/jquery.tocify.js
    - static/js/jquery.tocify.ori.js
    - static/js/jquery-ui.min.js

- name: install OSCA binaries
  copy:
    src: "{{ role_path }}/files/build/download/"
    dest: "/var/www/html/cnsgenomics.com/software/osca/download/"
    owner: apache
    group: apache
    mode: 0644
